### ISSUE TITLE
关于在NVIDIA上的跟踪速度问题

### ISSUE THREAD

**Issue by Jiangsiping** [chenxin-dlut/HCAT#1]
作者您好，我最近在做一份关于在NVIDIA NX上部署实时目标跟踪算法的任务。baseline由resnet18,3个encoder,和5层全连接网络构成的预测头组成，在NX板上测试UAV123数据集，速度为20.9帧，在1660TI上，速度为103帧。但是，后续无论是将encoder的数量降为2，还是将5层卷积的预测头换成3层，或者将通道数由256降为192，在NX板上速度分别提升至22.6，21.2，21.9，在1660TI上分别提升至112，109，116。以上修改动均减少了大量参数，为什么跟踪速度没有明显提升呢？我该如何去定位问题呢？期待您的回复！

**Comment by chenxin-dlut** [comment]
你好，其实实际应用时，计算量并不能代表算法速度，访存量、代码实现都会有影响，我在论文中也有提到。我建议可以测试一下代码不同部分的速度，看看时间主要耽误在哪了，包括模型本身forward的速度，以及图像的前后处理速度(包括生成搜索区域等)，进行针对性优化。
另外onnx加速的效果是十分明显的，如果在嵌入式平台上部署，建议一定要使用onnx或tensorrt等工具加速。
